In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("../datasets/data/train.csv")
df.head()

,qtype,Question,Answer
0,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,LCMV infections can occur after exposure to fr...
1,symptoms,What are the symptoms of Lymphocytic Choriomen...,LCMV is most commonly recognized as causing ne...
2,susceptibility,Who is at risk for Lymphocytic Choriomeningiti...,Individuals of all ages who come into contact ...
3,exams and tests,How to diagnose Lymphocytic Choriomeningitis (...,"During the first phase of the disease, the mos..."
4,treatment,What are the treatments for Lymphocytic Chorio...,"Aseptic meningitis, encephalitis, or meningoen..."

In [10]:
df["question_answer"]  = "Question: " + df["Question"].astype(str) + ". " + "Type: " + df["qtype"].astype(str) + ". " + "Answer: " + df["Answer"].astype(str) + ". "

del df["qtype"]
del df["Question"]
del df["Answer"]

df.head()

                                     question_answer
0  Question: Who is at risk for Lymphocytic Chori...
1  Question: What are the symptoms of Lymphocytic...
2  Question: Who is at risk for Lymphocytic Chori...
3  Question: How to diagnose Lymphocytic Choriome...
4  Question: What are the treatments for Lymphocy...